### ISSUE TITLE
SSR workflow

### ISSUE THREAD

**Issue by fusionstrings** [WebReflection/udomsay#3]
First of all, many thanks for this initiative.
I am trying to explore this library for potential production workflows.
The Counter example works for client side but SSR seems to be broken or may be I am overlooking something.

The tests for SSR also seems to be broken. If it's broken because of WIP stuff, that's fine.

A minimal example for client and SSR will be very nice.

**Comment by WebReflection** [comment]
Everything is broken now so either you try 0.1.x or you wait for me to fix this library. The issue comes from ESX at its third iteration and every iteration was a breaking Chang but latest version is stable and has it all yet I haven’t had the time to fully replace it in here. Apologies for the situation

**Comment by fusionstrings** [comment]
Thanks for the response 🙏.
I totally understand, as I have been following the progress on multiple fronts on ESX including https://es.discourse.group/t/proposal-esx-as-core-js-feature/1511

Wishing you all the best.
I will use the latest/stable version in mean time.

**Comment by WebReflection** [comment]
Check js-framework-benchmark as the confit there works

**Comment by fusionstrings** [comment]
Thanks, I looked at the example but those are client-side only. Even 0.4.0 (which is also latest) works client side, it's SSR which is don't work for me.

**Comment by WebReflection** [comment]
nothing works now unless exact config used in that benchmark which should work SSR too but I won't do anything until the rewrite is done.

**Comment by WebReflection** [comment]
it's up https://github.com/WebReflection/udomsay#readme ... you can see the SSR example here: https://github.com/WebReflection/udomsay/blob/main/test/ssr.jsx

**Comment by WebReflection** [comment]
P.S. there is no hydration right now, SSR simply vomits out HTML without listeners and without effects. I need to wrap my head around *how* to automatically provide hydration as that would be more than desired but for the time being it just works as it's meant to: just produce clean HTML without side-effects ever run.

**Comment by fusionstrings** [comment]
Thanks a lot for getting this to work.
Since this fulfils my wish, I am closing the issue. 🥇 💯

**Comment by fusionstrings** [comment]
Here is example in use https://github.com/fusionstrings/esx-playground
